version: "3.9"
   
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:7000
    volumes:
      - .:/code
    ports:
      - "7000:7000"
    depends_on:
      - db


