version: '3.8'

services:

  python:
      build: ""
      command: python db_interaction.py
      #links:
      #  - "database:db"
      networks:
      - sql_dump_cloudmanager

networks:
  sql_dump_cloudmanager:
    external: true
