name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      with: # Set the secret as an input
	HOST: ${{ secrets.host }}
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
	ping -c 5 ${{ secrets.HOST }}
